### ISSUE TITLE
Request: Make Canopy Glass more transparent

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/optica#10]
Since the Optica is a sight-seeing/observation aircraft it would be nice if the interior canopy glass was made less foggy and more transparent,  please make it at least as clear as the default C172 as shown below.
C172
![20230519070753_1](https://github.com/krzysk1/optica/assets/69315126/e4dfc82b-6508-47a1-944b-0c253e01bfdd)
![20230519070907_1](https://github.com/krzysk1/optica/assets/69315126/79e91e72-e072-4123-8d6d-f192e3487487)

Optica
![20230519070831_1](https://github.com/krzysk1/optica/assets/69315126/1d2cf73f-84f0-4983-a91a-ed7fc76b081f)
![20230519070835_1](https://github.com/krzysk1/optica/assets/69315126/821c3702-59ed-4193-8aed-956537a4c722)

**Comment by krzysk1** [comment]
done

**Comment by krzysk1** [comment]
done
