### ISSUE TITLE
Odd wing flexture causes gap in wing 

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/optica#11]
Noticed that wing flexture when in flight causes gap to appear in wing surfaces as shown.
On ground
![20230616055822_1](https://github.com/krzysk1/optica/assets/69315126/084e0497-c36a-4ef5-af64-9d1f569aa241)

In the air 
![20230616055901_1](https://github.com/krzysk1/optica/assets/69315126/3e66c1f8-9e42-435d-bf31-2d287126aa76)

**Comment by krzysk1** [comment]
done (or cannot be reproduced)
