### ISSUE TITLE
RIghtWingAero Flap0Area and Flap1Area Undefined

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/optica#3]
<[float64][Flap0Area][0.300]>
                <[float64][Flap1Area][0.300]>
Are not present in the RightWingAero block
Not sure if this is an issue, although deploying flaps up to 50 degrees does seem to cause a tendency to roll to the right.
            <[aerowing][LeftWingAero][]
                <[string8][Body][LeftWing]>
                <[float64][Span][6.000]>
                <[float64][Area][8.400]>
                <[string8][Flap0Control][ServoLeftAileron.Output]>
                <[string8][Flap1Control][ServoFlaps.Output]>
                <[float64array][StationY]           [ 0.000 1.798 3.595 5.992 ]>
                <[float64array][StationLE]          [ 0.455 0.440 0.425 0.405 ]>
                <[float64array][StationTE]          [ -1.045 -1.000 -0.955 -0.895 ]>
                <[float64array][StationZ]           [ -0.090 0.004 0.098 0.224 ]>
                <[float64array][StationIncidence]   [ 0.087 0.000 0.000 0.000 ]>
                <[uint32array][StationFlap]         [ 0 2 1 0 ]>
                <[float64array][StationFlapFraction][ 0.00 0.30 0.30 0.00 ]>
                <[float64][AspectRatioMultiplier][2.0]>
                <[string8][AirfoilRoot][AirfoilRoot]>
                <[string8][AirfoilTip][AirfoilTip]>
                <[float64][Flap0Area][0.300]>
                <[float64][Flap1Area][0.300]>
                <[string8][DownWashInput][LeftWingAero.DownWashMean]>
                <[float64][DownWashPercentage][1.00]>
                <[float64][GroundEffectFactor][1.00]>
                <[float64][GroundEffectScale][1.00]>
            >
But these two parameters are not present in the 
            <[aerowing][RightWingAero][]
                <[string8][Body][RightWing]>
                <[string8][Flap0Control][ServoRightAileron.Output]>
                <[string8][Flap1Control][ServoFlaps.Output]>
                <[float64array][StationY]           [ -5.992 -3.595 -1.798 0.000 ]>
                <[float64array][StationLE]          [ 0.405 0.425 0.440 0.455 ]>
                <[float64array][StationTE]          [ -0.895 -0.955 -1.000 -1.045 ]>
                <[float64array][StationZ]           [ 0.224 0.098 0 0.004 -0.090 ]>
                <[float64array][StationIncidence]   [ 0.000 0.000 0.000 0.087 ]>
                <[uint32array][StationFlap]         [ 1 2 0 0 ]>
                <[float64array][StationFlapFraction][ 0.30 0.30 0.00 0.00 ]>
                <[float64][AspectRatioMultiplier][2.0]>
                <[string8][AirfoilRoot][AirfoilRoot]>
                <[string8][AirfoilTip][AirfoilTip]>
                <[string8][DownWashInput][RightWingAero.DownWashMean]>
                <[float64][DownWashPercentage][1.00]>
                <[float64][GroundEffectFactor][1.00]>
                <[float64][GroundEffectScale][1.00]>

**Comment by jayeye2011** [comment]
I think the Flap0Area and Flap1Area duplicate the StationFlapFraction array and were probably deprecated in FS2 since there is no actual text description of what they are in the Wiki. I suggest removing them from LeftAeroWing rather than adding them to RightAeroWing. But leaving it unchanged with on wing having and the other not does induce a significant right roll effect when flaps are set to maximum 50 degrees. 
Edit: Note that right now, the Optical has an a slight tendency to roll left at all times when flaps are at 0 degrees. I guess that is just P-factor or something since propwash settings are negligeble.

**Comment by jayeye2011** [comment]
After removing the Flap0Area and Flap1Area defines from LeftWingAero this corrected the induce right roll when flaps fully deployed. Also the current Github optica.tmd still generates the following when maintaining constant altitude 
![20230107051953_1](https://user-images.githubusercontent.com/69315126/211152892-d21cb889-7d41-463d-a6fb-f45b06b3a0ec.jpg)
The Wikipedia specs for EA-7
Maximum speed: 213 km/h (132 mph, 115 kn)
Cruise speed: 130 km/h (81 mph, 70 kn) (loiter speed, 40% power)
Stall speed: 108 km/h (67 mph, 58 kn) outboard flaps up
[Never exceed speed](https://en.wikipedia.org/wiki/V_speeds#Vne): 259 km/h (161 mph, 140 kn)

**Comment by krzysk1** [comment]
Flap0Area and Flap1Area are deprecated, indeed. StationFlapFraction is used instead of.
Span and Area are deprecated as well

**Comment by jayeye2011** [comment]
It is important to remove 
<[float64][Flap0Area][0.300]>
<[float64][Flap1Area][0.300]>
from the left wing.
Since even though deprecated, if one wing has it defined while the other does not it does impact the flight model negatively in that deploying flaps induces and unbalance lift on the left wing causing the aircraft to roll to the right.

**Comment by krzysk1** [comment]
be removed next version

**Comment by jayeye2011** [comment]
> be removed next version

good enough
