### ISSUE TITLE
Compass inverted

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/optica#4]
Heading South but cockpit indicators show heading of North?
![20221229070545_1](https://user-images.githubusercontent.com/69315126/209972188-da00496e-1500-4677-8e8c-622d4dc0356a.jpg)

**Comment by krzysk1** [comment]
Gyro is not animated yet. will be fixed

**Comment by krzysk1** [comment]
headings corrected (gyro and other navigation eq will be updated)
