### ISSUE TITLE
Current GitHub Version Does Not Stall Either

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/optica#7]
After discovering that my heavily modified version of the wilga.tmd file will not stall, I installed the current main branch version (last updated 23 December 2022 to stall test it. It does not stall either. Here is a screenshot at 0% throttle, full back stick, 100% nose up trim.
![NoStallingGitHubVersion](https://user-images.githubusercontent.com/69315126/213401378-63815ab7-aac3-4125-8bb4-93b4660feec6.jpg)

**Comment by krzysk1** [comment]
https://www.buckarooshangar.com/flightgear/Optica_readme.html

"The aircraft can almost float to the ground with no power and the stick held back. This is the reported behavior of the real aircraft. "
