### ISSUE TITLE
Trim  Position Indicator Seem Reversed To Actual Positions 

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/optica#8]
The trim indicator (and trim wheel rotation) are reversed to what they should be. The TO position should indicate be nose up/tail down or up trim  while the VA position should be nose down/tail up or down trim. This is exactly opposition of how it currently displays as shown in these two screen shots of 100% Trim Up and 100% Trim Down.
![20230119011252_1](https://user-images.githubusercontent.com/69315126/213406710-0412f1d7-9ce4-41bc-85d9-9c72300b2f3b.jpg)
![20230119011321_1](https://user-images.githubusercontent.com/69315126/213406735-a3496df9-d545-4ce2-8cc3-758c3794f54b.jpg)

**Comment by krzysk1** [comment]
fixed
