### ISSUE TITLE
Optica nose wheel steering can only make wide turn

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/optica#9]
Trying to park or do a turnaround on a runway is difficult due to the nose wheel only having a 10 degree max deflection angle. Recommend changing this to 30 deg (0.52 radians)
            <[servoclassic][ServoSteering][]
                <[string8][Input][RudderInput.Output]>
                <[float64][Speed][1.0]>
                <[float64][P0][0.0]>
                <[float64][P1][0.52]>
            >
[20230209 30deg nosegear steering optica_tmd.zip](https://github.com/krzysk1/optica/files/10709963/20230209.30deg.nosegear.steering.optica_tmd.zip)

**Comment by krzysk1** [comment]
changed to 30deg
